### PR TITLE
[frontend] After verification of Youtube account, it's not able to redirect to the app  Fixed

### LINKED ISSUE #185: [frontend] After verification of Youtube account, it's not able to redirect to the app
**Note - Before starting to work on this issue, share your emailId so that I can whitelist it for you to test the oAuth feature**
## Description
Go to influencer registration form -> click on verify icon of youtube -> enter emailId and passworkd -> you will be able to be logged in but redirection doesn't happen
Screenshot 2024-07-04 at 11 33 22 PM

Below is the redirect urls added in the google cloud
Screenshot 2024-07-04 at 11 41 06 PM

### PR DESCRIPTION
**Pull request by Hemu21**
## Description

It inludes both frontend and backend changes to make you tube verification working.

## Issue

[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/185) resolve #185

### CODE REVIEW

File: frontend/screens/Influencer/components/AddHandles.js [hunk 1]
```diff
@@ -81,87 +91,44 @@ const AddHandles = ({ route, navigation }) => {
...
+        setYoutube(JSON.parse(user)?.displayName);
         break;
     }
     Alert.alert("Success", `Your ${platform} account has been verified!`);
   }, []);
 
   useEffect(() => {
-    console.log("AddHandles mounted. Route params:", route.params);
-
-    if (route.params?.social) {
```
Comment (Kajol-Kumari) [inline frontend/screens/Influencer/components/AddHandles.js:93]: are we not getting social details in the params?

**Review by Kajol-Kumari — APPROVED** [review]
