### PR TITLE
[Frontend] Integration the Brand Signup with Backend Fixed

### LINKED ISSUE #9: [Frontend] Integration the Brand Signup with Backend
## Description
Current frontend page is static, integrate the [Brand-Signup](https://github.com/Kajol-Kumari/InfluMart/blob/main/influmartFrontend/screens/BrandRegistrationForm.js) page with the backend API - 
https://github.com/Kajol-Kumari/InfluMart/blob/main/backend/controllers/brandController.js#L7

### PR DESCRIPTION
**Pull request by Hemu21**
## Description

backend is integrated for brand signup front-end

## Issue

[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/9) resolve #9

### CODE REVIEW

**Comment by Hemu21** [comment]
@Kajol-Kumari  can you please check.

File: frontend/screens/BrandAccountReviewNotification.js [hunk 1]
```diff
@@ -1,12 +1,31 @@
...
 
 
-const BrandAccountReviewNotification = () => {
-  const navigation = useNavigation();
+const BrandAccountReviewNotification = ({ route, navigation }) => {
+  const { payload } = route.params;
+
+  const registerBrand = async () => {
+    try {
+      const response = await fetch("http://192.168.160.76:3000/brands/signup", {
```
Comment (Kajol-Kumari) [inline frontend/screens/BrandAccountReviewNotification.js:12]: please read the endpoint from environment variable and add it in .env.sample so that we can use hosted endpoint in the deployed app

File: frontend/screens/OtpVerification.js [hunk 2]
```diff
@@ -1,34 +1,58 @@
...
+const OtpVerification = ({ route, navigation }) => {
+  const { payload } = route.params;
+  const [otp, setOtp] = React.useState("");
 
-const OtpVerification = () => {
-  const navigation = useNavigation();
+  const verifyOTP = async () => {
+    const { email } = payload;
+    try {
+      const response = await fetch("http://192.168.160.76:3000/otp/verifyOTP", {
```
Comment (Kajol-Kumari) [inline frontend/screens/OtpVerification.js:13]: same here, please use env variable

File: frontend/screens/BrandRegistrationForm.js [hunk 3]
```diff
@@ -1,187 +1,206 @@
...
-  const navigation = useNavigation();
+  const handleSubmit = async () => {
+    // Construct the payload
+    const payload = {
+      email,
+      password,
+      category: [brandType],
+      name: username,
+    };
+    if (!email || !password || !brandType || !username) {
```
Comment (Kajol-Kumari) [inline frontend/screens/BrandRegistrationForm.js:28]: can we please add email and password validation? Also, how are we making sure that username is unique?

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]

File: frontend/screens/BrandRegistrationForm.js [hunk 4]
```diff
@@ -1,187 +1,206 @@
...
+            <View style={[styles.depth2Frame02, styles.frameLayout]}>
+              <View style={styles.frameLayout}>
+                <View style={styles.depth4Frame02}>
+                  <Text style={[styles.email, styles.emailTypo]}>
+                    Brand Type
+                  </Text>
+                </View>
+                <View style={styles.depth4Frame1}>
+                  <View style={[styles.depth5Frame01, styles.depth5FrameBg]}>
+                    <TextInput
```
Comment (Kajol-Kumari) [inline frontend/screens/BrandRegistrationForm.js:131]: This should be the a dropDown and we can have below options to start with - 
```
- grocery
- electronics
- fashion 
- toys 
- beauty
- home-decor
- fitness
- education
```

**Review by Kajol-Kumari — COMMENTED** [review]
@Hemu21  can we please rename the file `BrandAccountReviewNotification.js` to `BrandAccountSignupDataPreview.js`

File: frontend/screens/BrandAccountReviewNotification.js (hunk 1 above)
Comment (Hemu21) [reply frontend/screens/BrandAccountReviewNotification.js]: ok

File: frontend/screens/OtpVerification.js (hunk 2 above)
Comment (Hemu21) [reply frontend/screens/OtpVerification.js]: ok

File: frontend/screens/BrandRegistrationForm.js (hunk 3 above)
Comment (Hemu21) [reply frontend/screens/BrandRegistrationForm.js:35]: added

File: frontend/screens/BrandRegistrationForm.js (hunk 4 above)
Comment (Hemu21) [reply frontend/screens/BrandRegistrationForm.js:142]: This issue includes only intrgation part. Ui enhancement is need for all the pages I had added backend integration. In next Issue I will make this and otp verifications ui enhancement. If you want I will add it in this issue or create one? ui enhancement is needed in 3 screens as the are previously not Inputs just text and images.

**Comment by Hemu21** [comment]
@Kajol-Kumari  please let me know can I include ui enhancement in this PR it self? then after mergining the brand signup is completly ready.

File: frontend/.env.sample [hunk 5]
```diff
@@ -0,0 +1 @@
+API_URL = http://192.168.160.76:3000
```
Comment (Kajol-Kumari) [inline frontend/.env.sample:1]: lets call it `API_ENDPOINT` it makes more sense

**Comment by Kajol-Kumari** [comment]
@Hemu21 which ui enhancement you are referring to?

File: frontend/.env.sample (hunk 5 above)
Comment (Hemu21) [reply frontend/.env.sample]: ok
