### PR TITLE
App Crashing In mobile Fixed

### LINKED ISSUE #253: App Crashing In mobile
## Description 

Need to go through entire app in mobile and check the where it is crashing and why it is crashing and fixing that bugs.

### PR DESCRIPTION
**Pull request by Hemu21**
## Description

Need to go through entire app in mobile and check the where it is crashing and why it is crashing and fixing that bugs. Now all bugs related to app crash is fixed.

## Issue

[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/253) resolve #253 

## Note

If anyone work on css or ui then make sure they used the fontweigt as string only not number.

### CODE REVIEW

File: frontend/util/ImageWithFallback.js [hunk 1]
```diff
@@ -17,7 +17,9 @@ const ImageWithFallback = ({ image, imageStyle }) => {
     require('../assets/influencer10.jpg'),
   ];
   useEffect(()=>{
-    if(!image){
+    if(!image || image == null || image == undefined){
```
Comment (Kajol-Kumari) [inline frontend/util/ImageWithFallback.js:20]: why if-else if we are calling the same `handleError`

Comment (Hemu21) [reply frontend/util/ImageWithFallback.js:20]: Why because it has different types are coming from db. and it rising to app crash in mobile. Above if is for image doesn't exist ot equal to null or undefined. if else is for if it retuns number of some other. form for string which image is not displayed.
