### PR TITLE
[Frontend] Integration the Influencers Signup with Backend Fixed

### LINKED ISSUE #10: [Frontend] Integration the Influencers Signup with Backend
## Description
Current frontend page is static, integrate the [Influencers-Signup](https://github.com/Kajol-Kumari/InfluMart/blob/main/influmartFrontend/screens/InfluencerRegistrationForm.js) page with its backend API  -
https://github.com/Kajol-Kumari/InfluMart/blob/main/backend/controllers/influencerController.js#L12

### PR DESCRIPTION
**Pull request by Hemu21**
## Description

Frontend and backend changes are included and influencer signup is completed.

## Issue

[Issue Link](https://github.com/Kajol-Kumari/InfluMart/issues/10) resolve #10

### CODE REVIEW

**Comment by Hemu21** [comment]
@Kajol-Kumari  @RohitGupta1237  can you please check and merge it.

File: frontend/screens/AddHandles.js [hunk 1]
```diff
@@ -0,0 +1,229 @@
...
+          }
+        >
+          <Text style={styles.confirmText}>Confirm</Text>
+        </TouchableOpacity>
+      </View>
+    </ScrollView>
+  );
+};
+
+const styles = StyleSheet.create({
```
Comment (Kajol-Kumari) [inline frontend/screens/AddHandles.js:135]: let's keep the styles in a separate file

File: frontend/screens/InfluencerConfirmAccount.js [hunk 2]
```diff
@@ -0,0 +1,485 @@
...
+          </View>
+        </View>
+      </View>
+    </ScrollView>
+  );
+};
+
+export default InfluencerConfirmAccount;
+
+const styles = StyleSheet.create({
```
Comment (Kajol-Kumari) [inline frontend/screens/InfluencerConfirmAccount.js:206]: similar here, lets keep the style and js file in a separate module called `influencer`

File: frontend/screens/MaxFollowersNo.js [hunk 3]
```diff
@@ -0,0 +1,191 @@
...
+          })
+        }
+      >
+        <Text style={styles.confirmButtonText}>Confirm</Text>
+      </TouchableOpacity>
+    </View>
+  );
+};
+
+const styles = StyleSheet.create({
```
Comment (Kajol-Kumari) [inline frontend/screens/MaxFollowersNo.js:98]: keep styles in a separate file

File: frontend/screens/PricePerPost.js [hunk 4]
```diff
@@ -0,0 +1,233 @@
...
+          }
+        >
+          <Text style={styles.confirmText}>Confirm</Text>
+        </TouchableOpacity>
+      </View>
+    </ScrollView>
+  );
+};
+
+const styles = StyleSheet.create({
```
Comment (Kajol-Kumari) [inline frontend/screens/PricePerPost.js:124]: same here, keep it separate

File: frontend/screens/UserProfilePhoto.js [hunk 5]
```diff
@@ -0,0 +1,177 @@
...
+          onPress={handleTakePhoto}
+        >
+          <Text style={[styles.buttonText, styles.takePhotoButtonText]}>Take Photo</Text>
+        </TouchableOpacity>
+      </View>
+    </View>
+  );
+};
+
+const styles = StyleSheet.create({
```
Comment (Kajol-Kumari) [inline frontend/screens/UserProfilePhoto.js:89]: same here, keep seaparate

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@Hemu21 few things - 
1. create a folder lets say `influencer` and keep all the influencer related pages/screens in there
2. Keep all the styles in a separate style file
3. The UI seems off, font size inconsistent, check the deploy preview and correct the same

**Comment by Hemu21** [comment]
@Kajol-Kumari  updated.

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]

**Comment by Kajol-Kumari** [comment]
Screenshot 2024-06-22 at 9 55 44 AM
the font is still looking inconsistent

File: backend/index.js [hunk 6]
```diff
@@ -33,11 +33,6 @@ const influencerAuthenticationMiddleware = require("./middleware/influencers/inf
 const influencerLoggingMiddleware = require("./middleware/influencers/influencerLoggingMiddleware");
 const { getSocialData } = require("./controllers/influencerController");
 
-// Middleware for Influencers
-app.use("/influencers", influencerAuthenticationMiddleware); // Authentication for influencers
```
[the remark this answers is not in the document]
Comment (Hemu21) [reply backend/index.js:37]: I removed from here and added in the influencers router page. Because if they are in index file authentication will apply for signup and login it leads to unable to login the user.

File: backend/model/Subscription.js [hunk 7]
```diff
@@ -3,12 +3,12 @@ const mongoose = require('mongoose');
 const subscriptionSchema = new mongoose.Schema({
   userName: { type: String, required: true, unique: true},
   plan: { type: String, required: true },
-  startDate: { type: Date, default: Date.now },
-  endDate: { type: Date, required: true },
+  startDate: { type: String, required: true },
+  endDate: { type: String},
```
[the remark this answers is not in the document]
Comment (Hemu21) [reply backend/model/Subscription.js:7]: @Kajol-Kumari  I am storing the formated duration like 2024-06-22 like. If you want to store it as normal date tye I will change.

**Comment by Hemu21** [comment]
> Screenshot 2024-06-22 at 9 55 44 AM the font is still looking inconsistent

Here everything is like I the design only.

**Comment by Kajol-Kumari** [comment]
@Hemu21 lets take ui fix in a separate pr 'coz the current ui looks very inconsistent
